version: "3.2"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - TZ=America/Fortaleza
      - MYSQL_ROOT_PASSWORD=dotproject
      - MYSQL_DATABASE=dotproject
      - MYSQL_USER=dotproject
      - MYSQL_PASSWORD=dotproject
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - /opt/docker/dpmysql:/var/lib/mysql
      # - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock   
  dockProject:
    depends_on:
      - "mysql"
    image: nilsonrsvieira/dockproject:1.0
    restart: always
    ports:
      - "80:80"
    links:
      - "mysql"